0713 task8
s-iwakawa/kintone_dojo pull request #10
Opened 2022-07-13 06:03 UTC by s-iwakawa

お疲れ様です。

タスク8の課題をプルリクエストしました。
フォルダ名：Task08
ファイル名：script.js
課題pdf：[URL](https://bozuman.cybozu.com/k/api/record/download.do/-/8.RESTAPI%E8%AA%B2%E9%A1%8C.pdf?app=21462&field=5424852&detectType=true&record=6&row=38409992&id=2741108&hash=48fbf2b6d6dcbd98d97c6008743e5edd74b1a5ba&revision=25&.pdf)

ご確認ほどよろしくお願いいたします。

2022-07-15 07:16 UTC, tokunagago requested changes
@s-iwakawa 概ねよく書けてます！
レビューで不明点あればいつでもどうぞ！

2022-07-15 07:16 UTC, tokunagago commented on Task08/script.js
> +			"app": 46,
開いているアプリを指定するときは `kintone.app.getId()` でアプリIDを指定できます！
（コードを移行したときに書き換えないで済むのでこっちのほうが汎用性がありますね）

```suggestion
			"app": kintone.app.getId(),
```

2022-07-15 07:16 UTC, tokunagago commented on Task08/script.js
> +				return 0;
参考（修正しなくてもOK）
比較するのはインデックスであり値が同じということはないはずなので `return 0` はなくてもOKですね。

そうすると三項演算子を使って少しシンプルに書くことができます！
```
orderedDropdown.sort((a,b) => {a.index < b.index ? -1 : 1);
```

2022-07-15 07:16 UTC, tokunagago commented on Task08/script.js
> +			};
31行目で `event.record.Table.value[0].value = []` として初期化して、
（初期化することでレコード追加画面で何も入らないドロップダウンを削除できる。）
34行目移行は `forEach` で `orderedDropdown` をすべてループさせたほうがよいかな！

```
event.record.Table.value = [];

Object.keys(orderedDropdown).forEach((key) => {
```

2022-07-20 01:11 UTC, s-iwakawa commented
レビューありがとうございます！
forEachでできました！同様にtask06も修正しておきます。

2022-07-20 08:24 UTC, tokunagago approved these changes
@s-iwakawa OKです！修正ありがとうございました！

2022-07-20 08:24 UTC, merged