0714 task09
s-iwakawa/kintone_dojo pull request #11
Opened 2022-07-14 01:35 UTC by s-iwakawa

お疲れ様です。

タスク9の課題をプルリクエストしました。
フォルダ名：Task09
ファイル名：script.js
課題pdf：[URL](https://bozuman.cybozu.com/k/api/record/download.do/-/9.RESTAPI%E8%AA%B2%E9%A1%8C.pdf?app=21462&field=5424852&detectType=true&record=21&row=541975637&id=2803494&hash=7dbf34b8e48431d0a18674bc15a40059a147f59a&revision=7&.pdf)

ご確認ほどよろしくお願いいたします。

2022-07-15 11:12 UTC, tokunagago requested changes
@s-iwakawa 全体的によく書けてます！
三項演算子も使いこなせていてGoodです！
レビューしたので確認をお願いします！

2022-07-15 11:12 UTC, tokunagago commented on Task09/script.js
> +			paramsQuery,
キーを追加してください！
（おそらく現状のコードだと重複していなくてもアラートが出ちゃうはず）

```suggestion
			query: paramsQuery,
```

2022-07-15 11:12 UTC, tokunagago commented on Task09/script.js
> +			return event;
正常動作の場合は `event` オブジェクトを変更していないので、
18行目の `return event;` はなくてOKです！（そのため18行目は不要になる）
また、23行目の `event.error` ですが、ユーザーが意図したキャンセルなのでエラーで処理をしないほうがよいですね。（サーバー接続失敗時や郵便番号を入力するところにひらがなを入力したりなど、ステータスコードがエラーコードになってたりシステムが意図してない操作があったときにエラーを出すのが一般的かな。）
正常時のように `window.alert` でキャンセルを知らせるか、`window.confirm` でキャンセルボタンを既に一度クリックしているのでアラートを出さなくてもよいと思います！

上記をふまえて、重複している場合のみの条件式を書けばOKです！
```
if (response.totalCount !== '0') {
  if (window.confirm('項目が重複しています。このまま保存しますか？')) {
    window.alert('保存しました');
  } else {  // elseと中括弧の間は半角スペースを1つ入れよう！
    return false;  // イベントハンドラーに対して、falseをreturnすると保存処理をキャンセルできる（課題資料4ページ目参照）
  }
}
```

または、条件式をつなげて次のようにも書けます！
```
if (response.totalCount !== '0' && !window.confirm('項目が重複しています。このまま保存しますか？')) {
	return false;
}
window.alert('保存しました');
```

2022-07-20 00:58 UTC, s-iwakawa commented on Task09/script.js
> +			return event;
>23行目の event.error ですが、ユーザーが意図したキャンセルなのでエラーで処理をしないほうがよいですね。（サーバー接続失敗時や郵便番号を入力するところにひらがなを入力して登録しようとしたときなど、ステータスコードがエラーコードになってたりシステムが意図してない操作があったときにエラーを出すのが一般的かな。）

承知しました！window.alertを削除して、return falseにしました。
動作確認できました！

2022-07-20 08:30 UTC, tokunagago approved these changes
@s-iwakawa ほぼOKです！
軽微な修正なので、修正してプッシュしたらセルフマージしてくだされ！

2022-07-20 08:30 UTC, tokunagago commented on Task09/script.js
> +				}
20行目のif文で条件式が true のときは何もしないのであれば、条件式に `!` をつけて `else` として書いている場合のみ書けばOK！

```suggestion
				if (!window.confirm('項目が重複しています。このまま保存しますか？')) {
				  return false;
				} 
```

2022-07-22 03:00 UTC, s-iwakawa commented
修正しました！
レビューありがとうございました！

2022-07-22 03:00 UTC, merged