Task04 0701
s-iwakawa/kintone_dojo pull request #6
Opened 2022-07-01 06:22 UTC by s-iwakawa

お疲れ様です。

タスク４の課題をプルリクエストしました。
フォルダ名：Task04
ファイル名：task4-1.html
                      task4-2.html
課題pdf：[PDFのURL](https://bozuman.cybozu.com/k/api/record/download.do/-/4.JavaScript%E8%AA%B2%E9%A1%8C.pdf?app=21462&field=5424852&detectType=true&record=2&row=37845535&id=2803564&hash=e8fbf5e7d8c9bcb2999ba16dde87be942f56197c&revision=34&.pdf)

ご確認ほどよろしくお願いいたします。

2022-07-04 01:52 UTC, d-taka-d commented on Task04/task4-1.html
> +  const storageOptionPrice = 1000; // ¥1000 per 10GB
ここの値はL49,L50から取得したいです。

2022-07-04 02:17 UTC, d-taka-d commented on Task04/task4-2.html
> +  const storageOptionPrice = 1000; // ¥1000 per 10GB
ここの値取得は4-1同様です
HTMLの要素から取得したい。

2022-07-04 02:29 UTC, d-taka-d commented on Task04/task4-2.html
> +  };
課題4-2の場合、L67 にあるid 'btn'要素をクリックしたときに計算が実行されればいいのでかなり短く記述することが出来ます。
大きな流れとしては
1. 'btn'クリック時に2つのclass "chk"要素それぞれをチェックされているかを確認
2.  チェックされている場合class "slct"要素のvalueを取得
3.  取得した値を利用してそれぞれの計算結果を初期値に加算
4. 加算した値でid "price"の値を書き換える

2022-07-04 02:53 UTC, d-taka-d commented on Task04/task4-1.html
> +  const chk1 = document.getElementsByClassName('chk')[0];
L70とL81で同じ処理を2回行っていますね
getElementsByClassNameの戻り値はHTMLCollectionといってインデックス番号でアクセスできる配列のような形で返ってくるので例えば
```
const chkArray = document.getElementsByClassName('chk’);
```
のような変数で取得してあげるとL71 、L82 が
```
chkArray[x].onchange= () =>{
}
```
の形で使うことで出来ます。
参考：https://lab.syncer.jp/Web/API_Interface/Reference/IDL/HTMLCollection/

2022-07-04 03:04 UTC, d-taka-d commented on Task04/task4-1.html
> +  };
関数化めちゃくちゃいいですね。
ただ今回の処理は
```
 return defPrice + secureOptionPrice * numOfUser + storageOptionPrice * ammount;
```
の1行で記載出来てしまう処理なんですよね。

また課題4-1の場合、それぞれのチェックボックスのオンオフタイミングで
L72 からL77 のセキュアアクセスの加減計算と
L82 からL87 のディスク容量追加の加減計算が行われます。
なのでL56 で定義されている'defPrice'をletで定義してあげたうえで
```
chk1.checked
```
がTrueになったら'defPrice'に値を加算
Falseになったら'defPrice'から値を減算するように記述すると関数化も必要なくコードをさらに減らすことが出来ます。

2022-07-04 03:04 UTC, d-taka-d commented
コメントしたので確認お願いします!

2022-07-08 08:26 UTC, s-iwakawa commented on Task04/task4-2.html
> +  };
とても短くまとめることができました！ありがとうございます。

2022-07-08 08:28 UTC, s-iwakawa commented on Task04/task4-1.html
> +  };
document.getElement ... で取得した型がstring だと気づくのに時間がかかり、手こずりました…
関数化せずできました！

2022-07-08 08:29 UTC, s-iwakawa commented
再度レビューのほどよろしくお願いいたします。

2022-07-12 08:48 UTC, d-taka-d commented
遅くなってすみません、確認します!

2022-07-13 12:03 UTC, d-taka-d commented on Task04/task4-1.html
> +  const chkArray = document.getElementsByClassName('chk');
document.getElementsByClassNameを3回繰り返してしまっているところだけ非常に惜しいです。

ここは
```
const chkArray = document.getElementsByClassName('chk');
````
で初めに変数にしてあげると以下のようにシンプルな記載が出来ます!
```
const secureOptionPrice =chkArray[0].value;
const storageOptionPrice = chkArray[1].value;
```

2022-07-13 12:11 UTC, d-taka-d commented on Task04/task4-2.html
> +  const secureOptionPrice = document.getElementsByClassName('chk')[0].value; // ¥250 per user
L73 、L74、L83 、L89で4回
```
`document.getElementsByClassName('chk')` 
``` 
を実行しているのでここは 変数化したいです。
4-1と同様ですが、始めに
```
const chkArray = document.getElementsByClassName('chk')
``` 
とすると移行は
chkArrayと[]によるインデックス指定で表現できますね

2022-07-13 12:13 UTC, d-taka-d commented on Task04/task4-2.html
> +    if (secureChk.checked) {
L90の if文も同様ですが、上でコメントしたchkArrayを利用すると、L83,L89で変数化している部分が必要なくif文の判定が行えます！

2022-07-13 12:19 UTC, d-taka-d commented
全体的にとてもよいです。
微修正だけおねがいします!

コードをシンプルにするところで、やはり変数化があると思いますが
複数回使うような部分は最初の方に変数化してあげると、そこ以降短く書くことが出来る。
逆に一回しか使わないようなところは、変数化、そのあとその変数にアクセスだと無駄に長くなるので
そのような場合は変数化せずにそのまま使うといった判断を行うとルールが出来て対応しやすくなると思います

↑はdojoだとgetElementsByClassNameを使うときなどが該当するかなと思います。

またtask3をマージしてしまったので見えるかわからないので以下は再掲になりますが
コードはとても良いので体裁など細かいところに気を使えるともっと良いと思います。
とはいえ自分で確認するのは難しい部分もあるので拡張機能を使うのがおすすめです。
例えば↓の拡張機能入れると意図してない半角スペースを見つけやすかったり
https://webrandum.net/vscode-trailing-spaces/

VSCODEでフォーマッターを設定することで最後に自動で整形してくれたりします。
この辺は好みがあるので自分に合うやつを探して入れていくと使いやすくなると思います。
https://maku.blog/p/qcoz9ju/

2022-07-14 04:30 UTC, s-iwakawa commented on Task04/task4-1.html
> +  const chkArray = document.getElementsByClassName('chk');
本当ですね！シンプルになりました！

2022-07-14 04:50 UTC, s-iwakawa commented
`const chkArray = document.getElementsByClassName('chk')`
これでコードを削減することができました！

「複数使うようなものをグローバル的に変数化し、一回しか使わないようなものはそのまま使う。」
勉強になります！

また、体裁など細かいところに気を付けることも忘れずにやっていきます！
Trailing space　入れました！

2022-07-15 10:22 UTC, tokunagago requested changes

2022-07-15 10:22 UTC, tokunagago commented on Task04/task4-2.html
> +  const calc = document.getElementById('btn').onclick = () => {
変数 `calc` は78行目以外で使用していないので削除してOKです！
```suggestion
  document.getElementById('btn').onclick = () => {
```

2022-07-15 10:23 UTC, tokunagago commented
@s-iwakawa （cc: @d-taka-d ）ほぼOKです！
軽微な修正なので、修正後セルフマージしてください！
お疲れ様でした！

2022-07-20 00:34 UTC, s-iwakawa commented
変数 calc は使っていませんでした！
関数にする必要があるかないのかも以降気をつけていきたいと思います。
レビューありがとうございました！

2022-07-20 00:35 UTC, merged