midterm 0708
s-iwakawa/kintone_dojo pull request #7
Opened 2022-07-08 08:35 UTC by s-iwakawa

お疲れ様です。

中間課題のレビューをお願いいたします。
フォルダ名：midterm

よろしくお願いいたします。

2022-07-11 02:48 UTC, s-iwakawa commented
すみません、URLを開くことを失念していました。修正して再度プッシュしますので、現在レビューされていたらすみませんがお待ちいただけると嬉しいです…

2022-07-11 06:12 UTC, s-iwakawa commented
commit 'modified url transition' で再度pushしました！
ご確認のほどよろしくお願いいたします！

2022-07-14 09:34 UTC, tokunagago requested changes
@s-iwakawa タスクの関係で中間課題以降は私がみることになりました！
レビューで不明点があれば遠慮なくどうぞ！

2022-07-14 09:34 UTC, tokunagago commented on midterm/script.js
> +  const row = Object.keys(newsData).forEach((key) => {
`row` は変数化した後に使用していないので `Object.keys` から書き始めてOKです！

さらに、`newsData` は配列なので
```
newsData.forEach((key) => {
```
とすることができます。
そうすることで構造が少しシンプルになり、
`newsData[key]` を `key` に書き換えることができます！
例
`tblDayData.textContent = key.day.value;` とか
`tblCategoryData.textContent = key.category.value;` みたいに。

（VSCodeで一括置換すると楽かも。参考：https://qiita.com/hayatokunn/items/76b41e00f114cf9a9f14 ）

2022-07-14 09:34 UTC, tokunagago commented on midterm/script.js
> +(async() => {
`async()`のカッコの前には半角スペースを1つ入れるのが一般的かな。

```suggestion
(async () => {
```

2022-07-14 09:34 UTC, tokunagago commented on midterm/script.js
> +    hrefInfo.target = '_blank'; //別ウィンドウで開く
`newsData` オブジェクトの中身を見ていくと `target` というキーがあるので、それの値を利用してください！
```suggestion
    hrefInfo.target = hrefInfo.target = key.target.value;
```

（本来はドメインが異なるサイトに移動する場合は別タブで開いたほうがよいのですが、今回は課題資料4ページ目に「targetが_selfなら同じウィンドウ、_blankなら別ウィンドウで開かせること」とあるので）

2022-07-14 09:34 UTC, tokunagago commented on midterm/script.js
> +      if (contentLength > maxLength) {
（修正しなくてもOK！）
`contentLength` はif文の条件式でのみ使われるので、変数化しなくてもOKです！
変数宣言を減らすことで、（基本的には）可読性があがるのとメモリを省力化できます！

```suggestion
      if (newsData[key].content.value.length > maxLength) {
```

2022-07-15 04:20 UTC, s-iwakawa commented
剛さん、この課題以降のレビューお願いいたします！
中間課題の修正しました。ご確認のほどよろしくお願いします。

2022-07-15 04:41 UTC, tokunagago commented
@s-iwakawa OKです！お疲れ様でしたー！

2022-07-15 04:41 UTC, merged