0712 task07
s-iwakawa/kintone_dojo pull request #8
Opened 2022-07-12 08:10 UTC by s-iwakawa

お疲れ様です。

タスク７の課題をプルリクエストしました。
フォルダ名：Task07
ファイル名：script.js
課題pdf：[DLURL](https://bozuman.cybozu.com/k/api/record/download.do/-/7.JSAPI%E8%AA%B2%E9%A1%8C.pdf?app=21462&field=5424852&detectType=true&record=20&row=541975620&id=2741097&hash=f421a94d262aafe8c18398a199ece5c187e49715&revision=4&.pdf)

ご確認のほどよろしくお願いいたします。

2022-07-14 10:56 UTC, tokunagago requested changes
@s-iwakawa よく書けてるね！
細かい修正ですが確認をお願いします！

2022-07-14 10:56 UTC, tokunagago commented on Task07/script.js
> +	kintone.events.on('app.record.edit.change.管理番号', avoidDuplication);
次のように書くことができます！
```suggestion
kintone.events.on([
    'app.record.create.change.日付',
    'app.record.edit.change.日付',
    'app.record.create.change.サイボウズ製品',
    'app.record.edit.change.サイボウズ製品',
    'app.record.create.change.管理番号',
    'app.record.edit.change.管理番号'
  ], avoidDuplication);
```

2022-07-14 10:56 UTC, tokunagago commented on Task07/script.js
> +		event.record.重複禁止項目_文字列.disabled = true;
レコード作成画面・編集画面を開いたときに編集不可にしたいので、別イベントにしてください！
イメージ
```
kintone.evnets.on([XXX.XXX.XXX, XXX.XXX.XXX], (event => {
  // 編集不可にする処理
}));

const avoidDuplication = // 省略

kintone.evnets.on([XXX.XXX.XXX, XXX.XXX.XXX], avoidDuplication);
```

2022-07-14 10:56 UTC, tokunagago commented on Task07/script.js
> +		} ;
関数化しないで1行で書くとスッキリします！
```suggestion
		const dateStr = event.record.日付.value.replace(/-/g, '');
```
注意：26行目も合わせて要変更

2022-07-14 10:56 UTC, tokunagago commented on Task07/script.js
> +		event.record.重複禁止項目_文字列.value = dateData() + '-' + productCode + '-' + manageNumber;
提案（修正しなくてもOK）
テンプレートリテラルを使うと `+` を書かなくて済みます！
```suggestion
		event.record.重複禁止項目_文字列.value = `${dateData()}-${productCode}-${manageNumber}`
```

2022-07-15 04:45 UTC, s-iwakawa commented on Task07/script.js
> +		event.record.重複禁止項目_文字列.disabled = true;
確かに、別イベントで初めから編集不可にする必要がありますね！

2022-07-15 04:46 UTC, s-iwakawa commented on Task07/script.js
> +		} ;
なんでも関数化する癖あります笑
高宮さんにもアドバイスいただきましたが、一回しか使わないところは関数化しないことを忘れないようにします。

2022-07-15 04:51 UTC, s-iwakawa commented on Task07/script.js
> +		event.record.重複禁止項目_文字列.value = dateData() + '-' + productCode + '-' + manageNumber;
クエリでバッククォートの有能さを知りました、、
+を書かないだけで楽になりましたが、今回のケースだと変数間の文字がハイフンなので少し見にくいのかなとも思いました！時と場合で使い分けていきます。

2022-07-15 04:51 UTC, s-iwakawa commented
修正しました！
ご確認のほどよろしくお願いいたします。

2022-07-22 03:16 UTC, tokunagago approved these changes

2022-07-22 03:17 UTC, tokunagago commented
@s-iwakawa レビュー遅れてごめん🙏🙏
OKです！

2022-07-22 03:17 UTC, merged