0712 task06
s-iwakawa/kintone_dojo pull request #9
Opened 2022-07-13 02:28 UTC by s-iwakawa

お疲れ様です。

タスク６のプルリクエストを忘れていました。
レビューのほどよろしくお願いいたします。

2022-07-14 09:55 UTC, tokunagago requested changes
@s-iwakawa よく書けてるね！
一箇所だけレビューしたので修正をお願いします！

2022-07-14 09:55 UTC, tokunagago commented on Task06/script.js
> +		for (let count = 1; count < Object.keys(dropdownData).length; count++) {
オブジェクトの要素数と同じ数分ループするので、`forEach` を使ったほうがわかりやすいかな！
```suggestion
		Object.keys(dropdownData).forEach((key) => {
```
注意：この変更によって、`value: dropdownData[count]` は、`value: dropdownData[key]` に変更する必要が出てくる

配列の要素数と同じ数分のループのときは`forEach`を使うと、
コードを読んだ人が「あ、配列の要素すべてを処理するんだな」ってわかるので少しだけ可読性があがります！
もしくは `for...of` を使ったり。
参考：https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/for...of
`for` は`break`を使って途中でループを抜け出すことができたり、単純に1つずつループしないときなどに使えるかな。

2022-07-15 05:01 UTC, s-iwakawa commented on Task06/script.js
> +		for (let count = 1; count < Object.keys(dropdownData).length; count++) {
本当はforEachでやりたかったのですが、今回テーブルを増やすために、pushをして追加しました。そのため、forEachすると、初期にある０番目の後に配列の数増やしてしまうため、一つ多く作成してしまう問題がありました。
それを解決するために、安直ではありますが、for で一つ飛ばしてforループを回す処理にしました。
１５行目　`event.record.Table.value[0].value.Action5.value = dropdownData[0];` 　はドロップダウンの値を代入しています。

やりたかったことは、
1. 初期テーブルに値を上書き
2. テーブル追加→代入　×５回

この課題でforEachを使うにはどうしたら良いでしょうか？

2022-07-20 01:19 UTC, s-iwakawa commented
@tokunagago 再度pushしました！task08で教えていただいたforEachでできました！
ご確認のほどよろしくお願い申し上げます。

2022-07-22 03:19 UTC, tokunagago approved these changes

2022-07-22 03:19 UTC, tokunagago commented
@s-iwakawa レビュー遅れてごめん🙏🙏
OKです！
これでdojo全部完了かな？お疲れ様でした！！
きっとコーディング力がぐっと向上したはず！！

2022-07-22 03:19 UTC, merged